on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@v0.14.0
        with:
          bump_version_scheme: minor
      - name: Check Output Parameters
        run: echo "Got version ${{ steps.release.outputs.tag_name }}"
